### ISSUE TITLE
ffmpeg error when attempting to export audio?

### ISSUE THREAD

**Issue by juggalombre** [DanRuta/xVA-Synth#20]
Originally, I thought this was due to me using the mp3 mode (as the temporary .wav file is still created and plays normally when I grab it)

But I can't seem to get audio files to export after updating - Previously, I was on 1.3.6 and exporting worked fine.

Below is a sample from server.log:

```
2021-07-20 02:07:02,345 - POST /outputAudio
2021-07-20 02:07:02,347 - audio options: {'hz': 22050, 'padStart': 0, 'padEnd': 0, 'bit_depth': 'pcm_s32le', 'amplitude': 1}
2021-07-20 02:07:02,348 - ffmpeg command: ffmpeg -i ./resources/app/output/temp-4752225620384505.wav -acodec pcm_s32le -af volume=1 -ar 22050 C:/Users/Kaz/Desktop/out/sk_delvin/You're my son. I can't let you just run off and get hurt.wav
2021-07-20 02:07:02,391 - Traceback (most recent call last):
  File "python\audio_post.py", line 39, in run_audio_post
  File "ffmpeg\_run.py", line 320, in run
  File "ffmpeg\_run.py", line 285, in run_async
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

This happens no matter what voice or what mode i choose. I _did_ accidentally wipe out my entire xVASynth folder when updating to 1.4.0, but I would've assumed that since i was "reinstalling" at that point (albiet by accident) exporting shouldn't have been an issue :?

I hope this is somehow user error, but I may as well open an issue here in case I'm not alone - Dr. Google said there was another issue _similar_ to this but it happened randomly, as opposed to consistently as here.

**Comment by juggalombre** [comment]
Wait the file literally says not found right. there. i apologise, 2AM is not a good time for troubleshooting. Will re-open if grabbing a fresh ffmpeg copy doesn't fix it.
