### ISSUE TITLE
Error generating batch voice for Cirilla

### ISSUE THREAD

**Issue by Ksardas178** [DanRuta/xVA-Synth#55]
I got a simple .csv file for batch synthesis here. The problem is that when I choose Cirilla's voice, batch generation doesn't work. I'll leave the traceback below. But the app works good if I choose other voices, such as Cerys (both from "The Witcher" game).

[BathSynthesis.csv](https://github.com/DanRuta/xVA-Synth/files/12841092/BathSynthesis.csv)
```
Traceback (most recent call last):
File "server.py", line 335, in do_POST
File "python\xvapitch\model.py", line 379, in infer_batch
File "C:\Users\Ksardas\Downloads\xVASynth v3.0.0 Main app-44184-3-0-0-1684850032\v3.0.0\.\resources\app\python\xvapitch\xvapitch_model.py", line 223, in infer_advanced
return self.infer_using_vals(logger, plugin_manager, cleaned_text, text, lang_embs, speaker_embs, pace, None, None, None, None, None, None, pitch_amp=pitch_amp)
File "C:\Users\Ksardas\Downloads\xVASynth v3.0.0 Main app-44184-3-0-0-1684850032\v3.0.0\.\resources\app\python\xvapitch\xvapitch_model.py", line 292, in infer_using_vals
x, x_emb, x_mask = self.text_encoder(input_symbols, x_lengths, lang_emb=None, stats=False, lang_emb_full=lang_emb_full)
File "torch\nn\modules\module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "C:\Users\Ksardas\Downloads\xVASynth v3.0.0 Main app-44184-3-0-0-1684850032\v3.0.0\.\resources\app\python\xvapitch\xvapitch_model.py", line 602, in forward
x = torch.cat((x_emb, lang_emb_full), dim=-1)
RuntimeError: Tensors must have same number of dimensions: got 3 and 5
```

**Comment by Ksardas178** [comment]
Seems to be fixed in patch v3.0.2
Sorry =/
